### ISSUE TITLE
Quest is not working. Error:"is not in the chain after 30 seconds"

### ISSUE THREAD

**Issue by schupat** [0rtis/dfktools#16]
I guess I'm doing something wrong, but I tried the quest_example.py and changed the **PrivateKey** and **heros_id**

Error I receive:

2022-02-10 09:00:38,248|DFK-quest|INFO: Waiting for transaction https://explorer.harmony.one/tx/<ID> to be mined
Traceback (most recent call last):
  File "/home/environments/dfk/lib/python3.8/site-packages/web3/eth.py", line 740, in wait_for_transaction_receipt
    _timeout.sleep(poll_latency)
  File "/home/environments/dfk/lib/python3.8/site-packages/web3/_utils/threads.py", line 89, in sleep
    self.check()
  File "/home/environments/dfk/lib/python3.8/site-packages/web3/_utils/threads.py", line 82, in check
    raise self
web3._utils.threads.Timeout: 30 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 35, in <module>
    quest.start_quest(quest_contract, my_heroes_id, 3, private_key, w3.eth.getTransactionCount(account_address), gas_price_gwei, tx_timeout)
  File "/home/environments/dfk/code/quest/quest.py", line 10, in start_quest
    return quest_core.start_quest(quest_address, hero_ids, attempts, private_key, nonce, gas_price_gwei, tx_timeout_seconds, self.rpc_address, self.logger)
  File "/home/environments/dfk/code/quest/quest_core.py", line 86, in start_quest
    tx_receipt = w3.eth.wait_for_transaction_receipt(transaction_hash=signed_tx.hash, timeout=tx_timeout_seconds,
  File "/home/environments/dfk/lib/python3.8/site-packages/web3/eth.py", line 744, in wait_for_transaction_receipt
    raise TimeExhausted(
web3.exceptions.TimeExhausted: Transaction HexBytes('<ID>') is not in the chain after 30 seconds

If I go to the explorer link, I also don't see the transaction. 

I guess I'm missing something?

**Comment by schupat** [comment]
I had to increase "gas_price_gwei = 15" to 30 and than it was working.
